### ISSUE TITLE
Start using BEM syntax for CSS classes

### ISSUE THREAD

**Issue by SamLau95** [calblueprint/calblueprint.org#112]
Thought this was a good idea. @vivekraghuram @wonjun @negativetwelve @kevintxwu any thoughts?

http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

**Comment by negativetwelve** [comment]
hmm since switching to React components for the frontend, I've been a big fan of using inline styles for each component so I don't have to worry about classes anymore haha. But, I've seen companies take an approach like this so I would say it's good to start using. 

If anyone is interested in the react inline styles, this guy has a cool presentation about it: http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html

**Comment by SamLau95** [comment]
@negativetwelve ++
